title:        Gwion
tagline:      A strongly timed musical programming language
paginate:     1
author:
  name:       Jérémie Astor
  url:        https://fennecdjay.github.io/Gwion/

github: [metadata]

gems:
  - jekyll-gist
  - jekyll-paginate
gem: 'github-pages'
markdown: kramdown
incremental: true

gist:
  noscript: false

#highlighter: rouge

exclude: [Gemfile, Gemfile.lock, site.sh, .gitignore, README.md, .help.zsh]

#baseurl: https://fennecdjay.github.io/Gwion
