#line 1 "src/ast/lexer.c"

#line 3 "src/ast/lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define gwion__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer gwion__create_buffer
#endif

#ifdef yy_delete_buffer
#define gwion__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer gwion__delete_buffer
#endif

#ifdef yy_scan_buffer
#define gwion__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer gwion__scan_buffer
#endif

#ifdef yy_scan_string
#define gwion__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string gwion__scan_string
#endif

#ifdef yy_scan_bytes
#define gwion__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes gwion__scan_bytes
#endif

#ifdef yy_init_buffer
#define gwion__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer gwion__init_buffer
#endif

#ifdef yy_flush_buffer
#define gwion__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer gwion__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define gwion__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state gwion__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define gwion__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer gwion__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define gwion_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state gwion_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define gwion_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state gwion_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define gwion_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack gwion_ensure_buffer_stack
#endif

#ifdef yylex
#define gwion_lex_ALREADY_DEFINED
#else
#define yylex gwion_lex
#endif

#ifdef yyrestart
#define gwion_restart_ALREADY_DEFINED
#else
#define yyrestart gwion_restart
#endif

#ifdef yylex_init
#define gwion_lex_init_ALREADY_DEFINED
#else
#define yylex_init gwion_lex_init
#endif

#ifdef yylex_init_extra
#define gwion_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra gwion_lex_init_extra
#endif

#ifdef yylex_destroy
#define gwion_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy gwion_lex_destroy
#endif

#ifdef yyget_debug
#define gwion_get_debug_ALREADY_DEFINED
#else
#define yyget_debug gwion_get_debug
#endif

#ifdef yyset_debug
#define gwion_set_debug_ALREADY_DEFINED
#else
#define yyset_debug gwion_set_debug
#endif

#ifdef yyget_extra
#define gwion_get_extra_ALREADY_DEFINED
#else
#define yyget_extra gwion_get_extra
#endif

#ifdef yyset_extra
#define gwion_set_extra_ALREADY_DEFINED
#else
#define yyset_extra gwion_set_extra
#endif

#ifdef yyget_in
#define gwion_get_in_ALREADY_DEFINED
#else
#define yyget_in gwion_get_in
#endif

#ifdef yyset_in
#define gwion_set_in_ALREADY_DEFINED
#else
#define yyset_in gwion_set_in
#endif

#ifdef yyget_out
#define gwion_get_out_ALREADY_DEFINED
#else
#define yyget_out gwion_get_out
#endif

#ifdef yyset_out
#define gwion_set_out_ALREADY_DEFINED
#else
#define yyset_out gwion_set_out
#endif

#ifdef yyget_leng
#define gwion_get_leng_ALREADY_DEFINED
#else
#define yyget_leng gwion_get_leng
#endif

#ifdef yyget_text
#define gwion_get_text_ALREADY_DEFINED
#else
#define yyget_text gwion_get_text
#endif

#ifdef yyget_lineno
#define gwion_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno gwion_get_lineno
#endif

#ifdef yyset_lineno
#define gwion_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno gwion_set_lineno
#endif

#ifdef yyget_column
#define gwion_get_column_ALREADY_DEFINED
#else
#define yyget_column gwion_get_column
#endif

#ifdef yyset_column
#define gwion_set_column_ALREADY_DEFINED
#else
#define yyset_column gwion_set_column
#endif

#ifdef yywrap
#define gwion_wrap_ALREADY_DEFINED
#else
#define yywrap gwion_wrap
#endif

#ifdef yyget_lval
#define gwion_get_lval_ALREADY_DEFINED
#else
#define yyget_lval gwion_get_lval
#endif

#ifdef yyset_lval
#define gwion_set_lval_ALREADY_DEFINED
#else
#define yyset_lval gwion_set_lval
#endif

#ifdef yyalloc
#define gwion_alloc_ALREADY_DEFINED
#else
#define yyalloc gwion_alloc
#endif

#ifdef yyrealloc
#define gwion_realloc_ALREADY_DEFINED
#else
#define yyrealloc gwion_realloc
#endif

#ifdef yyfree
#define gwion_free_ALREADY_DEFINED
#else
#define yyfree gwion_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyg->yytext_ptr -= yyg->yy_more_len; \
	yyleng = (int) (yy_cp - yyg->yytext_ptr); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 134
#define YY_END_OF_BUFFER 135
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[387] =
    {   0,
        0,    0,    0,    0,    0,    0,   11,   11,    0,    0,
        0,    0,    0,    0,  135,  133,   30,   29,   63,  133,
      133,   34,   61,   78,  133,   84,   85,   64,   58,   32,
       59,  100,   60,  128,  128,   91,   31,   70,   83,   72,
       90,   33,  130,   86,   87,   80,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,   88,   79,   89,   62,  133,   30,   24,
      133,   28,   27,   28,  134,   14,  134,  134,   11,   12,
       10,  134,    9,    7,  134,    6,   19,   18,   19,    4,
        2,    3,    1,   69,    0,  131,    0,  122,   54,  123,

       55,    0,   76,    0,    0,    0,    0,   48,    0,    0,
        0,   49,    0,    0,  129,   25,    0,  129,  128,    0,
      128,    0,   92,   82,   74,   36,   68,   35,   75,   81,
       56,    0,  130,    0,    0,  130,  130,  130,  130,  130,
      130,  112,  130,  130,  130,  130,  130,  130,  130,  130,
      106,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,    0,   77,    0,    0,   24,  123,  123,  123,
      123,   26,    0,   14,   13,   11,    0,    7,    9,    7,
        0,    6,    0,  123,   41,   45,  132,   39,   37,    0,
       38,   99,   40,  129,  127,  126,   52,    0,    0,   53,

       42,   94,   93,   47,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  115,   50,  130,  130,   65,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,   46,   71,   73,  123,  123,  123,  123,
      123,  123,    0,    0,    0,  127,  126,   43,   44,  130,
      130,  121,  130,  118,  130,  130,  130,   96,  107,  119,
      130,  130,  130,  116,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  123,  123,  123,
      123,  123,  123,  123,    0,    8,    0,    0,  130,  130,
      108,   95,  105,  130,  130,  130,  130,  130,  130,  130,

      130,  130,   66,  130,  130,  130,  130,  130,   67,  113,
      111,  123,  123,  123,  123,  123,  123,    8,    0,    0,
      130,  130,  130,  130,  130,  101,  130,  130,  130,  114,
      110,  102,  117,  130,  130,  120,  123,    0,   16,  123,
      123,  123,  123,    0,   20,    0,  130,  130,  130,   98,
      130,  130,  104,  103,  130,   51,  123,    0,   17,    0,
      123,    0,    0,   21,  125,  124,  109,   50,   97,   57,
        0,   15,  123,   23,    5,   15,   15,    0,    0,   23,
       23,    5,    0,   22,   22,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   30,   29,   29,   29,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   31,   49,   50,   51,   52,
       53,   54,   31,   55,   56,   57,   58,   59,   60,   61,
       62,   31,   63,   64,   65,   66,    1,   67,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   68,   69,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    2,    1,    1,    1,    3,    1,    1,    1,    4,
        3,    1,    1,    1,    1,    1,    5,    5,    6,    6,
        6,    1,    1,    1,    1,    5,    1,    1,    7,    7,
        8,    8,    8,    8,    1,    1,    1,    1,    8,    7,
        7,    7,    7,    7,    7,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[407] =
    {   0,
        0,   69,   70,   71,   73,   74,   76,   78,  109,    0,
      606,   79,   80,   85,  608,  610,  610,  610,  582,   79,
       87,  610,   79,   77,  570,  610,  610,  580,   80,   97,
       87,   99,   83,  155,  160,  582,  610,   98,  103,  105,
      610,  121,    0,  610,  578,  577,  562,  542,  544,   94,
       60,  134,  120,   83,  553,  553,  542,  540,  550,  142,
      138,  541,  545,  610,  158,  610,  610,  524,  188,  610,
      192,  610,  610,  587,  586,  610,  142,  610,  586,  610,
      610,  199,  585,  584,  568,    0,  610,  610,  540,  610,
      610,  610,  610,  610,  201,  610,  580,  610,  610,    0,

      610,  556,  610,  555,  570,  201,  553,  610,  552,  206,
      560,  610,  550,  558,  200,  610,  548,  205,  210,  213,
      206,    0,  610,  220,  610,  610,  610,  610,  610,  221,
      610,  547,    0,  111,  546,  162,  514,  526,  513,  528,
      515,    0,  513,  509,  506,  506,  507,  509,  507,  502,
        0,  498,  513,  200,  195,  503,  515,  506,  502,  498,
      206,  503,  524,  610,  189,  259,  610,  505,  165,  189,
      496,  610,  544,  610,  543,  543,  257,  542,  541,  540,
      524,    0,  215,    0,  610,  610,  610,  610,  610,  523,
      610,  610,  610,  250,  254,  243,  610,  513,  512,  610,

      610,  610,  610,  610,  489,  488,  482,  494,  489,  476,
      221,  476,  486,  478,  484,    0,  485,  485,  472,    0,
      469,  464,  465,  477,  462,  464,  461,  460,  462,  471,
      461,  465,  462,  610,  610,  610,  466,  454,  466,  236,
      466,  464,  278,  450,  462,  249,  252,  610,  610,  454,
      451,    0,  453,    0,  445,  443,  451,    0,    0,    0,
      446,  440,  456,    0,  455,  454,  449,  452,  436,  441,
      441,  446,  437,  252,  434,  435,  440,  435,  438,  433,
      436,  436,  428,  433,  294,  474,  431,  426,  429,  428,
        0,    0,    0,  419,  427,  421,  418,  410,  409,  423,

      407,  411,    0,  420,  414,  420,  415,  413,    0,    0,
        0,  405,  289,  411,  410,  396,  408,  450,  295,  406,
      411,  410,  380,  381,  383,    0,  378,  386,  372,    0,
        0,    0,    0,  368,  379,    0,  379,  306,  610,  311,
      420,  375,  415,  313,  610,  315,  377,  376,  367,    0,
      358,  354,    0,    0,  364,    0,  381,  317,  610,  375,
      332,  373,  319,  610,    0,    0,    0,    0,    0,    0,
      322,  321,  287,  298,    0,  292,  281,  301,  240,  253,
      249,    0,  202,  207,  123,  610,  325,  333,  341,  349,
      357,  365,  371,  379,  382,  390,  393,  396,  399,  405,

      412,  419,  426,  433,  436,  440
    } ;

static const flex_int16_t yy_def[407] =
    {   0,
      386,    1,  387,  387,  388,  388,  389,  389,  389,    9,
      390,  390,  391,  391,  386,  386,  386,  386,  386,  392,
      393,  386,  386,  386,  394,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  395,  386,  386,  386,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  386,  386,  386,  386,  386,  386,  386,
      393,  386,  386,  386,  396,  386,  396,  386,  386,  386,
      386,  386,  386,  386,  386,  397,  386,  386,  386,  386,
      386,  386,  386,  386,  392,  386,  392,  386,  386,  398,

      386,  386,  386,  386,  386,  394,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  399,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  395,  386,  386,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  386,  386,  386,  386,  386,  398,  398,  398,
      398,  386,  396,  386,  396,  386,  386,  386,  386,  386,
      386,  397,  386,  398,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  399,  386,  386,  386,  386,

      386,  386,  386,  386,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  386,  386,  386,  398,  398,  398,  398,
      398,  398,  386,  386,  386,  386,  386,  386,  386,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  398,  398,  398,
      398,  398,  398,  398,  386,  386,  386,  386,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,

      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  398,  398,  398,  398,  398,  398,  386,  386,  386,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  398,  386,  386,  398,
      398,  398,  398,  386,  386,  386,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  398,  386,  386,  400,
      398,  401,  386,  386,  395,  395,  395,  395,  395,  395,
      402,  403,  398,  404,  405,  386,  403,  386,  406,  386,
      404,  405,  406,  386,  386,    0,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386
    } ;

static const flex_int16_t yy_nxt[681] =
    {   0,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   43,
       43,   43,   43,   43,   44,   16,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   43,   55,   43,   43,
       43,   56,   57,   58,   59,   60,   61,   62,   43,   63,
       43,   43,   64,   65,   66,   67,   16,   16,   16,   68,
       69,   70,   73,   73,   71,   76,   76,   79,   80,   79,
       80,   88,   78,   96,   89,  103,   81,   78,   81,  101,
       91,   92,   98,  108,   93,   91,   92,   99,  110,   93,

      116,  104,  112,  102,  109,   74,   74,  117,   77,   77,
       82,  113,  142,  111,   97,  114,  143,  115,  115,  115,
       83,  124,  125,   84,  385,   85,  126,  127,  128,  129,
      130,  131,  149,  139,  202,  150,  203,   86,   86,   86,
       86,   86,   86,  140,  174,  132,  141,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,  118,  147,  119,  119,  119,  118,  148,  119,  119,
      119,  159,  163,  144,  120,  145,  121,  121,  122,  166,
      167,  121,  121,  175,  146,  156,  120,   98,  157,  160,

      177,  158,   99,  386,  121,   96,  205,  110,  385,  121,
      105,  206,  121,  178,  238,  122,  239,  121,  115,  115,
      115,  164,  111,  194,  194,  194,  118,  384,  119,  119,
      119,  195,  195,  240,  168,  169,   97,  121,  121,  170,
      241,  121,  121,  197,  198,  199,  200,  222,  224,  171,
      380,  225,  223,  231,  380,  121,  235,  236,  177,  121,
      166,  167,  232,  121,  244,  384,  245,  121,  194,  194,
      194,  178,  195,  195,  247,  247,  256,  257,  281,  285,
      246,  246,  376,  247,  247,  246,  246,  282,  378,  286,
      338,  339,  247,  376,  307,  285,  344,  345,  246,  380,

      247,  247,  378,  246,  308,  286,  246,  338,  339,  247,
      379,  246,  358,  359,  344,  345,  363,  364,  358,  359,
      363,  364,  376,  371,  379,   72,   72,   72,   72,   72,
       72,   72,   72,   75,   75,   75,   75,   75,   75,   75,
       75,   78,   78,   78,   78,   78,   78,   78,   78,   87,
       87,   87,   87,   87,   87,   87,   87,   90,   90,   90,
       90,   90,   90,   90,   90,   95,   95,   95,   95,   95,
       95,   95,   95,  100,  362,  373,  360,  100,  100,  105,
      105,  105,  371,  105,  105,  105,  105,  133,  133,  133,
      173,  173,  173,  173,  173,  173,  173,  173,  182,  182,

      182,  184,  184,  184,  196,  196,  372,  370,  369,  368,
      367,  372,  372,  374,  366,  365,  362,  361,  374,  374,
      375,  360,  357,  356,  355,  375,  375,  377,  354,  353,
      352,  377,  377,  377,  381,  351,  350,  349,  381,  381,
      381,  382,  382,  382,  383,  383,  383,  383,  348,  347,
      346,  318,  343,  342,  341,  340,  337,  336,  335,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  281,  315,
      314,  313,  312,  311,  310,  309,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,

      292,  291,  290,  289,  288,  287,  284,  283,  280,  279,
      278,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  255,  254,  253,  252,  251,  250,  249,  248,  192,
      243,  180,  179,  180,  176,  174,  174,  242,  237,  234,
      233,  230,  229,  228,  227,  226,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  204,  201,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  386,  183,  181,  180,  179,  176,  174,  172,
      165,  162,  161,  155,  154,  153,  152,  151,  138,  137,

      136,  135,  134,  123,  107,  106,   94,  386,   88,   15,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386
    } ;

static const flex_int16_t yy_chk[681] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    3,    4,    2,    5,    6,    7,    7,    8,
        8,   12,   13,   20,   12,   24,    7,   14,    8,   23,
       13,   13,   21,   29,   13,   14,   14,   21,   30,   14,

       33,   24,   31,   23,   29,    3,    4,   33,    5,    6,
        9,   31,   51,   30,   20,   32,   51,   32,   32,   32,
        9,   38,   38,    9,  385,    9,   39,   39,   39,   40,
       40,   42,   54,   50,  134,   54,  134,    9,    9,    9,
        9,    9,    9,   50,   77,   42,   50,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,   34,   53,   34,   34,   34,   35,   53,   35,   35,
       35,   61,   65,   52,   34,   52,   34,   34,   34,   69,
       69,   35,   35,   77,   52,   60,   34,   71,   60,   61,

       82,   60,   71,  106,   34,   95,  136,  110,  384,   35,
      106,  136,   34,   82,  169,   34,  169,   35,  115,  115,
      115,   65,  110,  118,  118,  118,  119,  383,  119,  119,
      119,  120,  120,  170,   71,   71,   95,  121,  121,   71,
      170,  119,  119,  124,  124,  130,  130,  154,  155,   71,
      381,  155,  154,  161,  380,  121,  165,  165,  177,  119,
      166,  166,  161,  121,  183,  379,  183,  119,  194,  194,
      194,  177,  195,  195,  196,  196,  211,  211,  240,  243,
      246,  246,  377,  247,  247,  195,  195,  240,  373,  243,
      313,  313,  196,  376,  274,  285,  319,  319,  246,  374,

      196,  247,  378,  195,  274,  285,  246,  338,  338,  247,
      373,  195,  340,  340,  344,  344,  346,  346,  358,  358,
      363,  363,  372,  371,  378,  387,  387,  387,  387,  387,
      387,  387,  387,  388,  388,  388,  388,  388,  388,  388,
      388,  389,  389,  389,  389,  389,  389,  389,  389,  390,
      390,  390,  390,  390,  390,  390,  390,  391,  391,  391,
      391,  391,  391,  391,  391,  392,  392,  392,  392,  392,
      392,  392,  392,  393,  362,  361,  360,  393,  393,  394,
      394,  394,  357,  394,  394,  394,  394,  395,  395,  395,
      396,  396,  396,  396,  396,  396,  396,  396,  397,  397,

      397,  398,  398,  398,  399,  399,  400,  355,  352,  351,
      349,  400,  400,  401,  348,  347,  343,  342,  401,  401,
      402,  341,  337,  335,  334,  402,  402,  403,  329,  328,
      327,  403,  403,  403,  404,  325,  324,  323,  404,  404,
      404,  405,  405,  405,  406,  406,  406,  406,  322,  321,
      320,  318,  317,  316,  315,  314,  312,  308,  307,  306,
      305,  304,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  290,  289,  288,  287,  286,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  275,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  263,  262,  261,  257,  256,

      255,  253,  251,  250,  245,  244,  242,  241,  239,  238,
      237,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  219,  218,  217,  215,  214,  213,
      212,  210,  209,  208,  207,  206,  205,  199,  198,  190,
      181,  180,  179,  178,  176,  175,  173,  171,  168,  163,
      162,  160,  159,  158,  157,  156,  153,  152,  150,  149,
      148,  147,  146,  145,  144,  143,  141,  140,  139,  138,
      137,  135,  132,  117,  114,  113,  111,  109,  107,  105,
      104,  102,   97,   89,   85,   84,   83,   79,   75,   74,
       68,   63,   62,   59,   58,   57,   56,   55,   49,   48,

       47,   46,   45,   36,   28,   25,   19,   15,   11,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() (yyg->yy_more_flag = 1)
#define YY_MORE_ADJ yyg->yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "utils/gwion.l"
#line 3 "utils/gwion.l"
#include <stdio.h>
#include <ctype.h>
#include "absyn.h"
#include "hash.h"
#include "scanner.h"
#include "parser.h"
#include "err_msg.h"
#define gwion_alloc(a,b) xmalloc(a)
#define gwion_realloc(a,b,c) xrealloc(a,b)
#define gwion_free(a,b)  xfree(a)
#define YY_FATAL_ERROR(msg) gwion_fatal_error(msg, yyscanner)

ANN static void yynoreturn gwion_fatal_error (const char* msg , yyscan_t yyscanner);
ANN static char* strip_lit(char* str);
ANN static char* alloc_str(const char* str);
ANN static long htol(const char* str);
ANN static int newline(void* data);
ANN static void adjust(void* data);
ANN static int  get_currline(void* data);
ANN static char* get_currfile(void* data);
ANN int gwion_error(Scanner* scan, const char* s);
ANN int get_pos(const Scanner* scan);
ANN static Macro add_macro(void* data, const m_str id);
ANN static m_str strip_include(Scanner* scan, const m_str line, const m_bool);
ANN2(1,2) static void handle_include(void*, const m_str, YY_BUFFER_STATE);
ANN static void rem_macro(void* data, const m_str id);
ANN static int has_macro(void* data, const m_str id, const m_bool);
ANN static int macro_toggle(void*);
ANN static void macro_end(void*);
ANN2(1,2) static int is_macro(void*, const m_str, YY_BUFFER_STATE);
ANN static void macro_append(void*, const m_str);
ANN static void macro_arg(void* data, const m_str id);

/* macro call args */
ANN static void handle_comma(void* data);
ANN static void handle_lpar(void* data);
ANN static int  handle_rpar(void* data);

// we should use yymore instead
ANN void handle_char(void* data, const m_str str);

ANN static m_str strip_comment(Scanner* scan, const m_str str);
ANN static m_str get_arg_text(void* data, const m_str id);
#ifdef LINT_MODE
ANN static m_str macro_data(void* data, const m_bool);
#define SCAN_LINT(a)        if(scan->lint)a;
#define SCAN_NOLINT      if(!scan->lint)
#define GWYY_ISLINT      ((Scanner*)yyextra)->lint
#define GWYY_DOLINT(a)   if(GWYY_ISLINT) { a; }
#define GWYY_LINT(a,b)   if(GWYY_ISLINT) { yylval->sval = a; return b; }
#else
#define SCAN_LINT(a)
#define SCAN_NOLINT
#define GWYY_DOLINT
#define GWYY_LINT(a,b)
#endif
#define GWYY_COMMENT     GWYY_DOLINT(yymore()); continue;
#define GWYY_COMMENT2    GWYY_DOLINT(yymore()); newline(yyscanner); continue;
#define GWYY_COMMENT_END GWYY_LINT(strip_comment(yyscanner, yytext), PP_COMMENT) continue;

#define GWYY_INCLUDE GWYY_LINT(strip_include(yyscanner, yytext, 1), PP_INCLUDE) handle_include(yyscanner, yytext, YY_CURRENT_BUFFER);
#define GWYY_UNDEF   GWYY_LINT(strdup(yytext), PP_UNDEF) rem_macro(yyscanner, yytext);
#define GWYY_DEFINE  GWYY_LINT(macro_data(yyscanner, 0), PP_DEFINE) newline(yyscanner);
#define GWYY_CALL    GWYY_LINT(macro_data(yyscanner, 1), ID)
#define GWYY_NL      GWYY_LINT(NULL, PP_NL)
#define GWYY_IFDEF(a,b) GWYY_LINT(strdup(a + b), b ? PP_IFNDEF : PP_IFDEF) if(!has_macro(yyscanner, a, !b)) BEGIN(skip); xfree(a);
#define GWYY_ELSE    GWYY_LINT(NULL, PP_ELSE) BEGIN(macro_toggle(yyscanner));
#define GWYY_ENDIF   GWYY_LINT(NULL, PP_ENDIF) macro_end(yyscanner);

#line 992 "src/ast/lexer.c"

#line 994 "src/ast/lexer.c"

#define INITIAL 0
#define comment 1
#define define 2
#define define_arg_start 3
#define define_arg 4
#define skip 5
#define get_arg 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 92 "utils/gwion.l"

#line 1259 "src/ast/lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yyg->yy_more_len = 0;
		if ( yyg->yy_more_flag )
			{
			yyg->yy_more_len = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			yyg->yy_more_flag = 0;
			}
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 387 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 386 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 93 "utils/gwion.l"
{ adjust(yyscanner); handle_comma(yyscanner); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 94 "utils/gwion.l"
{ adjust(yyscanner); handle_lpar(yyscanner); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 95 "utils/gwion.l"
{ adjust(yyscanner); if(handle_rpar(yyscanner)) { BEGIN(INITIAL); GWYY_CALL }}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 96 "utils/gwion.l"
{ adjust(yyscanner); handle_char(yyscanner, yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 98 "utils/gwion.l"
{
  add_macro(yyscanner, yytext);
  BEGIN(define_arg_start);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 102 "utils/gwion.l"
{ adjust(yyscanner); macro_arg(yyscanner, yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 103 "utils/gwion.l"
{ adjust(yyscanner); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 104 "utils/gwion.l"
{ adjust(yyscanner); macro_arg(yyscanner, "__VA_ARGS__"); BEGIN(define); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 105 "utils/gwion.l"
{ adjust(yyscanner); BEGIN(define); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 107 "utils/gwion.l"
{ adjust(yyscanner); BEGIN(define_arg); };
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 108 "utils/gwion.l"
{ adjust(yyscanner); BEGIN(define); };
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 109 "utils/gwion.l"
{ adjust(yyscanner); BEGIN(INITIAL); GWYY_DEFINE };
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 111 "utils/gwion.l"
{ adjust(yyscanner); macro_append(yyscanner, yytext); continue; /* should we use "\n" ? */ };
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 112 "utils/gwion.l"
{ adjust(yyscanner); macro_append(yyscanner, yytext); BEGIN(INITIAL); GWYY_DEFINE };
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 114 "utils/gwion.l"
{
//  adjust(yyscanner);
  const m_bool def = yytext[3] == 'n';
  Scanner* scan = yyget_extra(yyscanner);
  scan->pos += 7;
  const m_str text = strip_comment(yyscanner, yytext + 6 + def);
  GWYY_IFDEF(text, def)
}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 122 "utils/gwion.l"
{ newline(yyscanner); GWYY_ELSE }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 123 "utils/gwion.l"
{ newline(yyscanner); GWYY_ENDIF; BEGIN(INITIAL); }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 125 "utils/gwion.l"
{ newline(yyscanner); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 126 "utils/gwion.l"
{ continue;}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 127 "utils/gwion.l"
{ BEGIN(macro_toggle(yyscanner)); }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 128 "utils/gwion.l"
{ macro_end(yyscanner); BEGIN(INITIAL); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 130 "utils/gwion.l"
{ GWYY_INCLUDE }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 132 "utils/gwion.l"
{ GWYY_UNDEF }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 134 "utils/gwion.l"
{ newline(yyscanner); GWYY_NL; continue; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 136 "utils/gwion.l"
{ BEGIN(comment); }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 137 "utils/gwion.l"
{ newline(yyscanner); GWYY_COMMENT2 }
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 138 "utils/gwion.l"
{ newline(yyscanner); BEGIN(INITIAL); GWYY_COMMENT_END; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 139 "utils/gwion.l"
{ GWYY_COMMENT;  }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 141 "utils/gwion.l"
{ newline(yyscanner); continue; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 142 "utils/gwion.l"
{ adjust(yyscanner); continue; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 143 "utils/gwion.l"
{ adjust(yyscanner); return SEMICOLON;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 144 "utils/gwion.l"
{ adjust(yyscanner); return COMMA;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 145 "utils/gwion.l"
{ adjust(yyscanner); return ATSYM;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 146 "utils/gwion.l"
{ adjust(yyscanner); return DOLLAR;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 147 "utils/gwion.l"
{ adjust(yyscanner); return CHUCK;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 148 "utils/gwion.l"
{ adjust(yyscanner); return UNCHUCK;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 149 "utils/gwion.l"
{ adjust(yyscanner); return PLUSCHUCK;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 150 "utils/gwion.l"
{ adjust(yyscanner); return MINUSCHUCK;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 151 "utils/gwion.l"
{ adjust(yyscanner); return TIMESCHUCK;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 152 "utils/gwion.l"
{ adjust(yyscanner); return DIVIDECHUCK;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 153 "utils/gwion.l"
{ adjust(yyscanner); return MODULOCHUCK;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 154 "utils/gwion.l"
{ adjust(yyscanner); return ATCHUCK;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 155 "utils/gwion.l"
{ adjust(yyscanner); return RSL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 156 "utils/gwion.l"
{ adjust(yyscanner); return RSR;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 157 "utils/gwion.l"
{ adjust(yyscanner); return RSAND;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 158 "utils/gwion.l"
{ adjust(yyscanner); return RSOR;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 159 "utils/gwion.l"
{ adjust(yyscanner); return RSXOR;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 160 "utils/gwion.l"
{ adjust(yyscanner); return PLUSPLUS;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 161 "utils/gwion.l"
{ adjust(yyscanner); return MINUSMINUS;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 162 "utils/gwion.l"
{ adjust(yyscanner); return FUNCTION;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 163 "utils/gwion.l"
{ adjust(yyscanner); return TYPEDEF;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 164 "utils/gwion.l"
{ adjust(yyscanner); return L_HACK;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 165 "utils/gwion.l"
{ adjust(yyscanner); return R_HACK;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 166 "utils/gwion.l"
{ adjust(yyscanner); return SHARPPAREN;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 167 "utils/gwion.l"
{ adjust(yyscanner); return PERCENTPAREN;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 168 "utils/gwion.l"
{ adjust(yyscanner); return ATPAREN;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 169 "utils/gwion.l"
{ adjust(yyscanner); return TEMPLATE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 170 "utils/gwion.l"
{ adjust(yyscanner); return PLUS; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 171 "utils/gwion.l"
{ adjust(yyscanner); return MINUS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 172 "utils/gwion.l"
{ adjust(yyscanner); return DIVIDE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 173 "utils/gwion.l"
{ adjust(yyscanner); return PERCENT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 174 "utils/gwion.l"
{ adjust(yyscanner); return TILDA; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 175 "utils/gwion.l"
{ adjust(yyscanner); return EXCLAMATION; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 176 "utils/gwion.l"
{ adjust(yyscanner); return TIMES; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 177 "utils/gwion.l"
{ adjust(yyscanner); return NEW; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 178 "utils/gwion.l"
{ adjust(yyscanner); return SPORK; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 179 "utils/gwion.l"
{ adjust(yyscanner); return UNION; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 181 "utils/gwion.l"
{ adjust(yyscanner); return EQ; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 182 "utils/gwion.l"
{ adjust(yyscanner); return NEQ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 183 "utils/gwion.l"
{ adjust(yyscanner); return LT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 184 "utils/gwion.l"
{ adjust(yyscanner); return LTB; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 185 "utils/gwion.l"
{ adjust(yyscanner); return GT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 186 "utils/gwion.l"
{ adjust(yyscanner); return GTB; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 187 "utils/gwion.l"
{ adjust(yyscanner); return LE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 188 "utils/gwion.l"
{ adjust(yyscanner); return GE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 189 "utils/gwion.l"
{ adjust(yyscanner); return AND; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 190 "utils/gwion.l"
{ adjust(yyscanner); return OR; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 191 "utils/gwion.l"
{ adjust(yyscanner); return S_AND; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 192 "utils/gwion.l"
{ adjust(yyscanner); return S_OR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 193 "utils/gwion.l"
{ adjust(yyscanner); return S_XOR; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 194 "utils/gwion.l"
{ adjust(yyscanner); return SHIFT_RIGHT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 195 "utils/gwion.l"
{ adjust(yyscanner); return SHIFT_LEFT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 196 "utils/gwion.l"
{ adjust(yyscanner); return ASSIGN; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 197 "utils/gwion.l"
{ adjust(yyscanner); return LPAREN; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 198 "utils/gwion.l"
{ adjust(yyscanner); return RPAREN; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 199 "utils/gwion.l"
{ adjust(yyscanner); return LBRACK; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 200 "utils/gwion.l"
{ adjust(yyscanner); return RBRACK; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 201 "utils/gwion.l"
{ adjust(yyscanner); return LBRACE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 202 "utils/gwion.l"
{ adjust(yyscanner); return RBRACE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 203 "utils/gwion.l"
{ adjust(yyscanner); return QUESTION; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 204 "utils/gwion.l"
{ adjust(yyscanner); return COLON; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 205 "utils/gwion.l"
{ adjust(yyscanner); return COLONCOLON; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 206 "utils/gwion.l"
{ adjust(yyscanner); return TRIG; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 207 "utils/gwion.l"
{ adjust(yyscanner); return UNTRIG; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 210 "utils/gwion.l"
{ adjust(yyscanner); return CLASS;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 211 "utils/gwion.l"
{ adjust(yyscanner); return AST_DTOR;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 212 "utils/gwion.l"
{ adjust(yyscanner); return OPERATOR;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 213 "utils/gwion.l"
{ adjust(yyscanner); return EXTENDS;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 214 "utils/gwion.l"
{ adjust(yyscanner); return ELLIPSE;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 215 "utils/gwion.l"
{ adjust(yyscanner); return DOT;}
	YY_BREAK
 /* storage modifiers */
case 101:
YY_RULE_SETUP
#line 218 "utils/gwion.l"
{ adjust(yyscanner); return GLOBAL;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 219 "utils/gwion.l"
{ adjust(yyscanner); return STATIC;}
	YY_BREAK
 /*access modifiers */
case 103:
YY_RULE_SETUP
#line 222 "utils/gwion.l"
{ adjust(yyscanner); return PROTECT;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 223 "utils/gwion.l"
{ adjust(yyscanner); return PRIVATE;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 224 "utils/gwion.l"
{ adjust(yyscanner); return CONST;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 226 "utils/gwion.l"
{ adjust(yyscanner); return IF;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 227 "utils/gwion.l"
{ adjust(yyscanner); return ELSE;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 228 "utils/gwion.l"
{ adjust(yyscanner); return BREAK;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 229 "utils/gwion.l"
{ adjust(yyscanner); return CONTINUE;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 230 "utils/gwion.l"
{ adjust(yyscanner); return RETURN;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 231 "utils/gwion.l"
{ adjust(yyscanner); return WHILE;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 232 "utils/gwion.l"
{ adjust(yyscanner); return DO;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 233 "utils/gwion.l"
{ adjust(yyscanner); return UNTIL;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 234 "utils/gwion.l"
{ adjust(yyscanner); return LOOP;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 235 "utils/gwion.l"
{ adjust(yyscanner); return FOR;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 236 "utils/gwion.l"
{ adjust(yyscanner); return GOTO;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 237 "utils/gwion.l"
{ adjust(yyscanner); return SWITCH;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 238 "utils/gwion.l"
{ adjust(yyscanner); return CASE;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 239 "utils/gwion.l"
{ adjust(yyscanner); return ENUM;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 240 "utils/gwion.l"
{ adjust(yyscanner); return TYPEOF;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 241 "utils/gwion.l"
{ adjust(yyscanner); return AUTO;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 243 "utils/gwion.l"
{ adjust(yyscanner); return PASTE; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 244 "utils/gwion.l"
{
  adjust(yyscanner);
  const m_str text = get_arg_text(yyscanner, yytext + 1);
  if(text) {
    yylval->sval = alloc_str(text);
    return STRING_LIT;
  } else {
    gw_err("can't stringify non argument token '%s'\n", yytext + 1);
    return 1;
  }
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 255 "utils/gwion.l"
{ adjust(yyscanner); yylval->ival = get_currline(yyscanner); return NUM;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 256 "utils/gwion.l"
{ adjust(yyscanner); yylval->sval = get_currfile(yyscanner); return STRING_LIT;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 258 "utils/gwion.l"
{ adjust(yyscanner); yylval->ival = htol(yytext);                 return NUM;        }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 259 "utils/gwion.l"
{ adjust(yyscanner); yylval->ival = atoi(yytext);                 return NUM;        }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 260 "utils/gwion.l"
{ adjust(yyscanner); yylval->ival = atoi(yytext);                 return NUM;        }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 261 "utils/gwion.l"
{ adjust(yyscanner); yylval->fval = atof(yytext);                 return FLOAT;      }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 262 "utils/gwion.l"
{
  adjust(yyscanner);
  const int ret = is_macro(yyscanner, yytext, 
YY_CURRENT_BUFFER);
  if(!ret) {
    yylval->sval = alloc_str(yytext);
    return ID;
  } else
    continue;

}
	YY_BREAK
case 131:
/* rule 131 can match eol */
YY_RULE_SETUP
#line 274 "utils/gwion.l"
{ adjust(yyscanner); yylval->sval = alloc_str(strip_lit(yytext)); return STRING_LIT; }
	YY_BREAK
case 132:
/* rule 132 can match eol */
YY_RULE_SETUP
#line 275 "utils/gwion.l"
{ adjust(yyscanner); yylval->sval = alloc_str(strip_lit(yytext)); return CHAR_LIT;   }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 276 "utils/gwion.l"
{ gw_err("error: stray in program\n"); return 1; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 278 "utils/gwion.l"
ECHO;
	YY_BREAK
#line 2034 "src/ast/lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(define):
case YY_STATE_EOF(define_arg_start):
case YY_STATE_EOF(define_arg):
case YY_STATE_EOF(skip):
case YY_STATE_EOF(get_arg):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 387 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 387 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 386);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

#define YYTABLES_NAME "yytables"

#line 278 "utils/gwion.l"

// LCOV_EXCL_LINE
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

ANN static void yynoreturn gwion_fatal_error (const char* msg , yyscan_t yyscanner) {
  struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
  Scanner* scan = (Scanner*)yyg->yyextra_r;
  scanner_post(scan);
  gw_err("%s\n", msg);
  yy_flush_buffer(yyg->yy_buffer_stack[yyg->yy_buffer_stack_top], yyscanner);
  yyg->yy_start = 1 + 2 * INITIAL;
  longjmp(scan->jmp, 1);
}

char* strip_lit(char* str){
  str[strlen(str)-1] = '\0';
  return str+1;
}

char* alloc_str(const char* str) {
  const Symbol sym = insert_symbol((m_str)str);
  return s_name(sym);
}

long htol(const char* str) {
  char * c = (char*)str;
  unsigned long n = 0;

  c += 2;
  while(*c) {
    n <<= 4;
    switch(*c) {
      case '0' ... '9':
        n += *c - '0';
        break;
      case 'a' ... 'f':
        n += *c - 'a' + 10;
        break;
      case 'A' ... 'F':
        n += *c - 'A' + 10;
        break;
    }
    c++;
  }
  return n;
}

static int newline(void* data) {
  Scanner* scan = yyget_extra(data);
  scan->line++;
  scan->pos = 1;
  return 1;
}

static int get_currline(void* data) {
  Scanner* scan = yyget_extra(data);
  return scan->line;
}

static char* get_currfile(void* data) {
  Scanner* scan = yyget_extra(data);
  return alloc_str((m_str)vector_back(&scan->filename));
}

static void adjust(void* data) {
  Scanner* scan = yyget_extra(data);
  scan->pos += gwion_get_leng((void*)data);
}

static void err_line(const Scanner* scan, const m_str filename) {
  m_uint n = 1;
  size_t len = 0;
  FILE* f = fopen(filename, "r");
  if(!f)return; //exit(67);
  fseek(f, 0, SEEK_SET);
  m_str line = NULL;
  while(getline(&line, &len, f) != -1) {
    if(n == scan->line) {
      gw_err("%s", line);
      break;
    }
    n++;
  }
  fclose(f);
  free(line);
}

static void err_marker(Scanner* scan) {
  while(--scan->pos > 0)
    gw_err(" ");
  gw_err("\033[1;31m^\033[0m\n");
}

ANN int gwion_error(Scanner* scan, const char* s) {
  const m_str name = (m_str)vector_back(&scan->filename);
  m_str filename = name;
  m_uint i = vector_size(&scan->filename) - 1;
  if(*filename == '@') {
    err_msg(PARSE_, 0, "in macro '%s'.", filename);
    while(*filename == '@') {
      i -= 5;
      filename = (m_str)vector_at(&scan->filename, i);
    }
  }
  err_msg(PARSE_, 0, "in file '%s'.", filename);
  err_msg(PARSE_, scan->line, "%s. at pos %i\n", s, scan->pos);
  err_line(scan, filename);
  err_marker(scan);
  return 0;
}

static inline void gwpp_error(Scanner* scan, char* s) {
  gwion_error(scan, s);
  gwion_fatal_error("in macro expansion", scan->scanner);
}

ANN int get_pos(const Scanner* scan) {
  return scan->line;
}

static Macro add_macro(void* data, const m_str line) {
  Scanner* scan = yyget_extra(data);
  scan->pos += 8;
  m_str id = strip_comment(data, line + 8);
  scan->entry = hadd(&scan->macros, id);
  xfree(id);
  if(!scan->entry)
    gwpp_error(scan, "macro already defined");
  else {
    scan->entry->line = scan->line;
    scan->entry->pos = scan->pos;
  }
  return scan->entry;
}

static m_str strip_include(Scanner* scan, const m_str line, const m_bool sign) {
  m_str str = line + 8;
  while(isspace(*str))++str;
  if(!sign)
    ++str;
  m_str end = strstr(str, ">");
  scan->pos += str - line;
  return strndup(str, strlen(str) - strlen(end) + sign);
}

static m_str strip_comment(Scanner* scan, const m_str s) {
  m_str str = s;
  while(isspace(*str))++str;
  m_uint end = strlen(str);
  while(isspace(str[--end]));
  scan->pos += str - s;
  return strndup(str, end + 1);
}

static void rem_macro(void* data, const m_str str) {
  Scanner* scan = yyget_extra(data);
  scan->pos += 6;
  const m_str id = strip_comment(scan, str+6);
  const m_bool ret = hrem(&scan->macros, id);
  xfree(id);
  if(ret)
    gwpp_error(scan, "undefined macro");
}

static int has_macro(void* data, const m_str id, const m_bool def) {
  Scanner* scan = yyget_extra(data);
  return scan->def.data[++scan->def.idx] = def ?
    !!hhas(&scan->macros, id) : !hhas(&scan->macros, id);
}

static void gwpp_stack(Scanner* scan, YY_BUFFER_STATE state, void* opt, const m_str str) {
  const Vector v = &scan->filename;
  vector_add(v, scan->pos);
  vector_add(v, scan->line);
  vector_add(v, (vtype)state);
  vector_add(v, (vtype)opt);
  vector_add(v, (vtype)str);
}

static void handle_include(void* data, const m_str filename, YY_BUFFER_STATE handle) {
  Scanner* scan = yyget_extra(data);
  const m_str str = strip_include(scan, filename, 0);
  FILE* f = fopen(str, "r");
  if(!f) {
    xfree(str);
    gwpp_error(scan, "file not found");
  }
  gwpp_stack(scan, handle, f, str);
  scan->pos = 1;
  scan->line = 1;
  yy_switch_to_buffer(yy_create_buffer(f, YY_BUF_SIZE, data), data);
}

#ifdef LINT_MODE
static m_str macro_data(void* data, const m_bool call) {
  Scanner* scan = yyget_extra(data);
  const Macro e = scan->entry;
  size_t elen = strlen(e->name);
  size_t len = elen + 2;
  Args args = e->base;
  if(args) {
    do {
      const m_str str = call ? args->text : args->name;
      len += strlen(str);
      if(args->next)
        len += 2;
    } while((args = args->next));
    len += 2;
  }
  if(!call && e->text)
    len += strlen(e->text) + 1;
  char c[len];
  size_t offset = elen;
  strcpy(c, e->name);
  args = scan->entry->base;
  if(args) {
    c[offset++] = '(';
    do {
      const m_str str = call ? args->text : args->name;
      strcpy(c + offset, str);
      offset += strlen(str);
      if(call) {
        xfree(args->text);
        args->text = NULL;
      }
      if(args->next) {
        strcpy(c + offset, ", ");
        offset += 2;
      }
    } while((args = args->next));
    c[offset++] = ')';
  }
  if(!call && e->text) {
    c[offset++] = ' ';
    strcpy(c + offset, e->text);
    offset += strlen(e->text);
  }
  c[offset] = '\0';
  scan->entry = NULL;
  return !call ? strdup(c) : s_name(insert_symbol(c));
}
#endif
static int macro_toggle(void* data) {
  Scanner* scan = yyget_extra(data);
  scan->def.data[scan->def.idx] = !scan->def.data[scan->def.idx];
  if(scan->def.data[scan->def.idx])
    return INITIAL;
  else
    return skip;
}

static void macro_arg(void* data, const m_str id) {
  const Scanner* scan = yyget_extra(data);
  const Args arg = new_args(id);
  if(scan->entry->base) {
    Args a = scan->entry->base;
    while(a->next)
      a = a->next;
    a->next = arg;
  } else
    scan->entry->base = arg;
}

static void macro_end(void* data) {
  Scanner* scan = yyget_extra(data);
  --scan->def.idx;
}

static int is_macro(void* data, const m_str s, YY_BUFFER_STATE handle) {
  Scanner* scan = yyget_extra(data);
  const m_bool is_str = s[0] == '#';
  m_str id = is_str ? s+1 : s;
  const m_str name = (m_str)vector_back(&scan->filename);
  Args arg = name[0] == '@' ? (Args)vector_at(&scan->filename,
    vector_size(&scan->filename) - 2) : NULL;
  while(arg) {
    if(!strcmp(id, arg->name)) {
      if(arg->text) {
        if(!is_str) {
          SCAN_NOLINT {
            m_str str;
            asprintf(&str, "@argument '%s'", arg->name);
            gwpp_stack(scan, handle, NULL, str);
            //scan->pos      = e->pos;
            //scan->line     = e->line;
            yy_scan_string(arg->text, data);
          }
        } else {
          if(!strcmp(arg->name, "__VA_ARGS__"))exit(16);// not enough args ?
          return 0;
        }
      }
      return 1;
    }
    arg = arg->next;
  }
  Macro e = hhas(&scan->macros, id);
  if(e) {
    scan->entry = e;
    if(e->text) {
      if(e->base) {
        e->args = e->base;
        SCAN_NOLINT {
          m_str str;
          asprintf(&str, "@macro '%s'", e->name);
          gwpp_stack(scan, handle, e->base, str);
          scan->pos      = e->pos;
          scan->line     = e->line;
        }
  char c;
  while(isspace(c = input(data)))++scan->pos;
  if(c != '(')
    gwpp_error(scan, "macro needs arguments");
  ++scan->npar;
  struct yyguts_t * yyg = (struct yyguts_t*)data;
  yyg->yy_start = 1 + 2 * get_arg;
        return 2;
      } else {
        SCAN_LINT(return 0);
        m_str str;
        asprintf(&str, "@macro '%s'", e->name);
        gwpp_stack(scan, handle, e->base, str);
        scan->pos  = e->pos;
        scan->line = e->line;
        yy_scan_string(e->text, data);
        return 1;
      }
    }
    return 1;
  }
  return 0;
}

static m_str get_arg_text(void* data, const m_str id) {
  Scanner* scan = yyget_extra(data);
if(!scan->entry)
  return NULL;
  if(vector_size(&scan->filename) < 2)
    return NULL;
  Args arg = (Args)vector_at(&scan->filename, vector_size(&scan->filename) - 2);
  while(arg) {
    if(!strcmp(id, arg->name))
      return arg->text ? arg->text : "";
    arg = arg->next;
  }
  return NULL;
}

static void macro_append(void* data, const m_str text) {
  Scanner* scan = yyget_extra(data);
  const size_t tlen = strlen(text);
  if(scan->entry->text) {
    const size_t len = strlen(scan->entry->text) - 1;
    scan->entry->text = (m_str)xrealloc(scan->entry->text, len + tlen + 1);
    strcpy(scan->entry->text + len, text);
  } else
    scan->entry->text = strndup(text, tlen - 1);
}

int clear_buffer(Vector v, void* data, const m_bool last) {
  const m_str name = (m_str)vector_pop(v);
  const void* info = (void*)vector_pop(v);
  const YY_BUFFER_STATE state = (YY_BUFFER_STATE)vector_pop(v);
  if(!last)
    yy_delete_buffer(state, data);
  if(name[0] != '@')
    fclose((FILE*)info);
  xfree(name);
  vector_pop(v);
  vector_pop(v);
  return vector_size(v);
}

int yywrap(void* data) {
  struct yyguts_t * yyg = (struct yyguts_t*)data;
  YY_BUFFER_STATE handle = yyg->yy_buffer_stack[yyg->yy_buffer_stack_top];
  Scanner* scan = yyget_extra(data);
  if(vector_size(&scan->filename) > 2) {
    const m_str name = (m_str)vector_pop(&scan->filename);
    const void* info = (void*)vector_pop(&scan->filename);
    const YY_BUFFER_STATE state = (YY_BUFFER_STATE)vector_pop(&scan->filename);
    yy_switch_to_buffer(state, data);
    yy_delete_buffer(handle, data);
    if(name[0] != '@')
      fclose((FILE*)info);
    else if(info)
      clean_args((Args)info);
    xfree(name);
    scan->pos  = vector_pop(&scan->filename);
    scan->line = vector_pop(&scan->filename);
    return 0;
  }
  return 1;
}

void handle_comma(void* data) {
  Scanner* scan = yyget_extra(data);
  Args a = scan->entry->args;
  if(strcmp(a->name, "__VA_ARGS__") && !(scan->entry->args = a->next))
    gwpp_error(scan, "too many arguments");
}

void handle_lpar(void* data) {
  Scanner* scan = yyget_extra(data);
  ++scan->npar;
}

static int handle_rpar(void* data) {
  Scanner* scan = yyget_extra(data);
  if(--scan->npar)
    return 0;
  if(scan->entry->args->next)
    gwpp_error(scan, "not enough arguments");
  scan->entry->args = NULL;
  SCAN_NOLINT
    yy_scan_string(scan->entry->text, data);
  return 1;
}

void handle_char(void* data, const m_str str) {
  Scanner* scan = yyget_extra(data);
  const Args a = scan->entry->args;
  if(!a->text) {
    a->text = malloc(32);
    scan->arg_cap = 32;
    scan->arg_len = 1;
    a->text[0] = *str;
    a->text[1] = '\0';
  } else {
    if(++scan->arg_len == scan->arg_cap)
      a->text = realloc(a->text, (scan->arg_len << 1));
    a->text[scan->arg_len- 1] = *str;
    a->text[scan->arg_len] = '\0';
  }
}


