#include "ctrl.h"
JIT_CTRL(String_Assign)     { ctrl_set_ex(ctrl); }
JIT_CTRL(Int_String_Assign)     { ctrl_set_ex(ctrl); }
JIT_CTRL(Float_String_Assign)   { ctrl_set_ex(ctrl); }
JIT_CTRL(Complex_String_Assign) { ctrl_set_ex(ctrl); }
JIT_CTRL(Polar_String_Assign)   { ctrl_set_ex(ctrl); }
JIT_CTRL(Vec3_String_Assign)    { ctrl_set_ex(ctrl); }
JIT_CTRL(Vec4_String_Assign)    { ctrl_set_ex(ctrl); }
JIT_CTRL(Object_String_Assign)  { ctrl_set_ex(ctrl); }
JIT_CTRL(Int_String)     { ctrl_set_ex(ctrl); }
JIT_CTRL(Float_String)   { ctrl_set_ex(ctrl); }
JIT_CTRL(Complex_String) { ctrl_set_ex(ctrl); }
JIT_CTRL(Polar_String)   { ctrl_set_ex(ctrl); }
JIT_CTRL(Vec3_String)    { ctrl_set_ex(ctrl); }
JIT_CTRL(Vec4_String)    { ctrl_set_ex(ctrl); }
JIT_CTRL(Object_String)  { ctrl_set_ex(ctrl); }
JIT_CTRL(String_Plus)     { ctrl_set_ex(ctrl); }
JIT_CTRL(Int_String_Plus)     { ctrl_set_ex(ctrl); }
JIT_CTRL(Float_String_Plus)   { ctrl_set_ex(ctrl); }
JIT_CTRL(Complex_String_Plus) { ctrl_set_ex(ctrl); }
JIT_CTRL(Polar_String_Plus)   { ctrl_set_ex(ctrl); }
JIT_CTRL(Vec3_String_Plus)    { ctrl_set_ex(ctrl); }
JIT_CTRL(Vec4_String_Plus)    { ctrl_set_ex(ctrl); }
JIT_CTRL(Object_String_Plus)  { ctrl_set_ex(ctrl); }
