void jit_ctrl_import_array  (struct Jit*);
void jit_ctrl_import_event  (struct Jit*);
//void jit_ctrl_import_fileio (struct Jit*);
void jit_ctrl_import_float  (struct Jit*);
void jit_ctrl_import_instr  (struct Jit*);
void jit_ctrl_import_int    (struct Jit*);
void jit_ctrl_import_string (struct Jit*);
void jit_ctrl_import_ugen   (struct Jit*);
void jit_ctrl_import_vararg (struct Jit*);
