#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE minimal_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via minimal_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void minimal_restart (FILE *input_file ,yyscan_t yyscanner );
void minimal__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE minimal__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void minimal__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void minimal__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void minimal_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void minimal_pop_buffer_state (yyscan_t yyscanner );

static void minimal_ensure_buffer_stack (yyscan_t yyscanner );
static void minimal__load_buffer_state (yyscan_t yyscanner );
static void minimal__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER minimal__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE minimal__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE minimal__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE minimal__scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *minimal_alloc (yy_size_t ,yyscan_t yyscanner );
void *minimal_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void minimal_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer minimal__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        minimal_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            minimal__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        minimal_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            minimal__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define minimal_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yynoreturn yy_fatal_error (yyconst char* msg ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 125
#define YY_END_OF_BUFFER 126
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[310] =
    {   0,
        0,    0,    0,    0,    3,    3,    0,    0,    0,    0,
      126,  124,   16,   15,   58,  124,  124,   20,   56,   75,
      124,   81,   82,   59,   53,   18,   54,  102,   55,  119,
      119,   88,   17,   67,   80,   69,   87,   19,  121,   83,
       84,   77,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,   85,   76,
       86,   57,    9,   10,    3,    2,   12,   13,   12,    7,
        6,    7,   66,    0,  122,    0,   50,   51,    0,   73,
        0,    0,    0,    0,   42,    0,   43,    0,  120,   11,
        8,    0,  120,  119,    0,  119,    0,   89,   79,   71,

       68,   22,   65,   21,   72,   78,    0,  121,    0,    0,
      121,  121,  121,  121,  109,  121,  121,  121,  121,  121,
      121,  121,  103,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,    0,
       74,   70,    3,   14,    0,   37,   27,    0,   31,  123,
       25,   23,   24,    4,    1,   26,  120,  118,  117,   48,
        0,    0,   38,   36,    0,   39,    0,   49,   28,   91,
       90,   33,  121,  121,  121,  121,  121,  121,  121,  121,
      112,  121,  121,  121,  121,   60,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,

      121,  121,  121,   32,    0,    5,   34,  118,  117,   29,
       40,   41,   30,  121,  115,  121,  121,   93,  104,  116,
      121,  121,  113,  121,  121,  121,  121,  121,  121,  101,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,   35,  105,   92,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,   63,  121,  121,
      121,  121,  121,   64,  110,  121,  108,  121,  121,  121,
      121,  121,  121,  121,  121,   98,  111,  107,   62,  121,
      114,  121,  121,   61,  121,  121,   96,  121,  121,  121,
      121,  100,  121,   99,  121,   46,  121,  106,   44,  121,

      121,   94,  121,   52,   45,   97,   95,   47,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   30,   31,   30,   30,   30,
       32,   32,   32,   32,   32,   33,   32,   32,   32,   32,
       32,   32,   32,   32,   34,   32,   32,   35,   32,   32,
       36,   37,   38,   39,   32,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   32,   49,   50,   51,   52,
       53,   54,   32,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    5,    5,    5,    5,    1,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[319] =
    {   0,
        0,    0,  403,  402,  401,  400,   65,   66,   67,   68,
      402,  407,  407,  407,  375,   68,  388,  407,   63,   66,
      362,  407,  407,  372,   62,  407,   61,   61,   71,   88,
       78,  374,  407,   68,   76,   87,  407,  370,    0,  407,
      369,  368,  338,   67,   38,   66,   71,  339,   88,  347,
      336,   76,  345,   87,   42,  336,  347,  339,  407,   89,
      358,  407,  407,  407,    0,  407,  407,  407,  365,  407,
      407,  369,  355,  119,  407,  378,  407,  407,  353,  353,
      351,  366,  134,  349,  407,  348,  407,  347,  130,  368,
      367,  344,  137,  142,  122,  132,    0,  407,  142,  143,

      407,  407,  343,  407,  145,  147,  342,    0,  128,  341,
      323,  310,  325,  312,    0,  310,  306,  303,  303,  304,
      306,  300,    0,  302,  298,  294,  309,  130,  136,  127,
      289,  298,  310,  301,  297,  293,  131,  291,  297,  317,
      317,  407,    0,  407,  323,  407,  407,  314,  407,  407,
      407,  407,  407,  407,  407,  407,  165,  173,  162,  407,
      313,  312,  407,  407,  311,  407,  310,  407,  407,  407,
      407,  407,  296,  291,  278,  276,  277,  287,  279,  285,
        0,  286,  274,  276,  281,    0,  269,  264,  265,  271,
      276,  275,  260,  273,  261,  258,  257,  259,  268,  258,

      262,  261,  258,  407,  280,  407,  407,  164,  168,  407,
      407,  407,  407,  257,    0,  249,  256,    0,    0,    0,
      251,  245,    0,  257,  245,  259,  258,  253,  248,    0,
      255,  239,  240,  243,  243,  248,  239,  146,  236,  237,
      246,  241,  407,    0,    0,  232,  240,  234,  230,  235,
      222,  221,  235,  234,  218,  222,  228,    0,  230,  224,
      230,  225,  220,    0,    0,  216,    0,  172,  173,  175,
      183,  185,  171,  177,  162,    0,    0,    0,    0,  213,
        0,  159,  170,    0,  165,  167,    0,  158,  157,  166,
      150,    0,  160,  407,  159,    0,  138,    0,    0,  104,

      104,    0,   83,    0,    0,    0,    0,    0,  407,  231,
      236,  241,  246,  251,  256,  258,  263,   80
    } ;

static yyconst flex_int16_t yy_def[319] =
    {   0,
      309,    1,  310,  310,  311,  311,  312,  312,  313,  313,
      309,  309,  309,  309,  309,  314,  309,  309,  309,  309,
      315,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  316,  309,
      309,  309,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  309,  309,
      309,  309,  309,  309,  317,  309,  309,  309,  309,  309,
      309,  309,  309,  314,  309,  314,  309,  309,  309,  309,
      309,  309,  315,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  318,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  309,  316,  309,  309,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  309,
      309,  309,  317,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  318,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  309,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  309,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,    0,  309,
      309,  309,  309,  309,  309,  309,  309,  309
    } ;

static yyconst flex_uint16_t yy_nxt[475] =
    {   0,
       12,   13,   14,   13,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       39,   39,   39,   39,   39,   40,   12,   41,   42,   39,
       43,   44,   45,   46,   47,   48,   39,   49,   39,   39,
       39,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       39,   39,   39,   59,   60,   61,   62,   68,   68,   71,
       71,   72,   72,   75,   78,   80,   85,   87,   69,   69,
       89,   89,   89,  159,   90,  135,   88,   86,   79,   91,
      115,   81,   99,  100,  116,   93,   92,   94,   94,   94,

      102,  103,  104,  136,   76,   93,  112,   94,   94,   94,
       96,   96,  105,  106,  140,  117,  113,  118,   95,  114,
       96,   96,   97,  120,   75,  308,  119,   96,  121,   95,
      128,  101,  123,  129,  131,   96,  309,   96,  124,  125,
      132,  158,  158,  133,   82,   96,  134,  307,   97,   89,
       89,   89,  170,  141,  171,   76,  157,  157,  157,   93,
      306,   94,   94,   94,   96,   96,  160,  161,  162,  163,
      165,  166,  167,  168,   96,   96,  190,  188,  200,  305,
      192,   96,  189,  193,  157,  157,  157,  201,  262,   96,
      191,   96,  158,  158,  209,  209,  208,  208,  263,   96,

      209,  209,  304,  303,  302,  208,  208,  301,  300,  299,
      298,  209,  297,  208,  296,  295,  294,  209,  293,  209,
      292,  208,  208,  291,  290,  209,  289,  288,  287,  286,
      208,   63,   63,   63,   63,   63,   65,   65,   65,   65,
       65,   67,   67,   67,   67,   67,   70,   70,   70,   70,
       70,   74,   74,   74,   74,   74,   82,   82,  285,   82,
       82,  108,  108,  143,  284,  143,  143,  143,  283,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  264,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,

      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      207,  206,  205,  204,  203,  202,  199,  198,  197,  196,
      195,  194,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  169,  164,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,
      309,  146,  145,  144,  142,  139,  138,  137,  130,  127,
      126,  122,  111,  110,  109,  107,   98,   84,   83,   77,

       73,  309,   66,   66,   64,   64,   11,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309
    } ;

static yyconst flex_int16_t yy_chk[475] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    8,    9,
       10,    9,   10,   16,   19,   20,   25,   27,    7,    8,
       28,   28,   28,  318,   29,   55,   27,   25,   19,   29,
       45,   20,   34,   34,   45,   31,   29,   31,   31,   31,

       35,   35,   35,   55,   16,   30,   44,   30,   30,   30,
       31,   31,   36,   36,   60,   46,   44,   46,   30,   44,
       30,   30,   30,   47,   74,  303,   46,   31,   47,   30,
       52,   34,   49,   52,   54,   31,   83,   30,   49,   49,
       54,   95,   95,   54,   83,   30,   54,  301,   30,   89,
       89,   89,  109,   60,  109,   74,   93,   93,   93,   94,
      300,   94,   94,   94,   96,   96,   99,   99,  100,  100,
      105,  105,  106,  106,   94,   94,  129,  128,  137,  297,
      130,   96,  128,  130,  157,  157,  157,  137,  238,   96,
      129,   94,  158,  158,  159,  159,  208,  208,  238,   94,

      209,  209,  295,  293,  291,  158,  158,  290,  289,  288,
      286,  159,  285,  208,  283,  282,  280,  209,  275,  159,
      274,  208,  158,  273,  272,  209,  271,  270,  269,  268,
      158,  310,  310,  310,  310,  310,  311,  311,  311,  311,
      311,  312,  312,  312,  312,  312,  313,  313,  313,  313,
      313,  314,  314,  314,  314,  314,  315,  315,  266,  315,
      315,  316,  316,  317,  263,  317,  317,  317,  262,  261,
      260,  259,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  242,  241,  240,  239,  237,  236,
      235,  234,  233,  232,  231,  229,  228,  227,  226,  225,

      224,  222,  221,  217,  216,  214,  205,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  187,  185,  184,  183,  182,  180,  179,
      178,  177,  176,  175,  174,  173,  167,  165,  162,  161,
      148,  145,  141,  140,  139,  138,  136,  135,  134,  133,
      132,  131,  127,  126,  125,  124,  122,  121,  120,  119,
      118,  117,  116,  114,  113,  112,  111,  110,  107,  103,
       92,   91,   90,   88,   86,   84,   82,   81,   80,   79,
       76,   73,   72,   69,   61,   58,   57,   56,   53,   51,
       50,   48,   43,   42,   41,   38,   32,   24,   21,   17,

       15,   11,    6,    5,    4,    3,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "gwion.l"
#line 4 "gwion.l"

#include "absyn.h"
#include "parser.h"

static char* strip_lit( char* str )
{
  str[strlen(str)-1] = '\0';
  return str+1;
}

static char* alloc_str( char* str )
{
  char* s = (char*)calloc(1,  strlen(str) + 1 );
  strcpy( s, str );
  return s;
}

static long htol( char* str )
{
char * c = str;
  unsigned long n = 0;

  c += 2;
  while( *c )
  {
    n <<= 4; 
    switch( *c )
    {
      case '1': case '2': case '3': case '4': case '5':
      case '6': case '7': case '8': case '9': case '0':
      n += *c - '0';
      break;

      case 'a': case 'b': case 'c': case 'd': case 'e': case 
      'f':
      n += *c - 'a' + 10;
      break;

      case 'A': case 'B': case 
      'C': case 'D': case 'E': 
      case 'F':
      n += *c - 'A' 
      + 10;
      break;
    }    
    c++;
  }
  return n;
}

static int newline(void*data)
{
  MyArg* arg = (MyArg*)map_get(scan_map, data);
  arg->line++;
  arg->pos = 1;
  return 1;
}
char *minimal_get_text (yyscan_t yyscanner );

static int doc_newline(void* data)
{
  MyArg* arg = (MyArg*)map_get(scan_map, data);
  arg->line++;
  arg->pos = 1;
  strcat(arg->doc_str, "\n");
  return 1;
}
 
static m_str doc_append(void* data, m_str str)
{
  MyArg* arg = (MyArg*)map_get(scan_map, data);
  sprintf(arg->doc_str, "%s%s", arg->doc_str, str);
  return arg->doc_str;
}

static m_str doc_set(void* data)
{
  MyArg* arg = (MyArg*)map_get(scan_map, data);
  return arg->doc_str;
}

static int doc_init(void* data)
{
  MyArg* arg = (MyArg*)map_get(scan_map, data);
  vector_append(arg->doc, "");
  //memset(arg->doc_str, 0, sizeof(arg->doc_str));
  return 1;
}
static int adjust(void* data);
static int doc_adjust(void* data, char* str);





#line 735 "lexer.c"

#define INITIAL 0
#define comment 1
#define cdoc 2
#define COMMENT 3
#define CDOC 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int minimal_lex_init (yyscan_t* scanner);

int minimal_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int minimal_lex_destroy (yyscan_t yyscanner );

int minimal_get_debug (yyscan_t yyscanner );

void minimal_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE minimal_get_extra (yyscan_t yyscanner );

void minimal_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *minimal_get_in (yyscan_t yyscanner );

void minimal_set_in  (FILE * _in_str ,yyscan_t yyscanner );

FILE *minimal_get_out (yyscan_t yyscanner );

void minimal_set_out  (FILE * _out_str ,yyscan_t yyscanner );

			int minimal_get_leng (yyscan_t yyscanner );

char *minimal_get_text (yyscan_t yyscanner );

int minimal_get_lineno (yyscan_t yyscanner );

void minimal_set_lineno (int _line_number ,yyscan_t yyscanner );

int minimal_get_column  (yyscan_t yyscanner );

void minimal_set_column (int _column_no ,yyscan_t yyscanner );

YYSTYPE * minimal_get_lval (yyscan_t yyscanner );

void minimal_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int minimal_wrap (yyscan_t yyscanner );
#else
extern int minimal_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int minimal_lex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int minimal_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			minimal_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				minimal__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		minimal__load_buffer_state(yyscanner );
		}

	{
#line 109 "gwion.l"


#line 1017 "lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 310 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 407 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 111 "gwion.l"
{ BEGIN(cdoc); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 112 "gwion.l"
{ newline(yyscanner); BEGIN(INITIAL); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 113 "gwion.l"
{ adjust(yyscanner); yylval->sval = alloc_str(yytext); return DOC;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 116 "gwion.l"
{ BEGIN(CDOC); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 117 "gwion.l"
{ adjust(yyscanner); BEGIN(INITIAL); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 118 "gwion.l"
{ newline(yyscanner);  strcat(yylval->sval, "\n\n"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 119 "gwion.l"
{ adjust(yyscanner); yylval->sval =  strndup(yytext, strlen(yytext) - 4); return DOC;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 121 "gwion.l"
{ BEGIN(comment); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 122 "gwion.l"
{ adjust(yyscanner); continue;}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 123 "gwion.l"
{ newline(yyscanner); BEGIN(INITIAL); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 127 "gwion.l"
{ BEGIN(COMMENT); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 128 "gwion.l"
{ adjust(yyscanner); continue;}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 129 "gwion.l"
{ newline(yyscanner); continue;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 130 "gwion.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 133 "gwion.l"
{ newline(yyscanner); continue; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 134 "gwion.l"
{ adjust(yyscanner); continue; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 135 "gwion.l"
{ adjust(yyscanner); return SEMICOLON;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 136 "gwion.l"
{ adjust(yyscanner); return COMMA;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 137 "gwion.l"
{ adjust(yyscanner); return ATSYM;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 138 "gwion.l"
{ adjust(yyscanner); return DOLLAR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 139 "gwion.l"
{ adjust(yyscanner); return CHUCK;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 140 "gwion.l"
{ adjust(yyscanner); return UNCHUCK;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 141 "gwion.l"
{ adjust(yyscanner); return PLUSCHUCK;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 142 "gwion.l"
{ adjust(yyscanner); return MINUSCHUCK;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 143 "gwion.l"
{ adjust(yyscanner); return TIMESCHUCK;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 144 "gwion.l"
{ adjust(yyscanner); return DIVIDECHUCK;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 145 "gwion.l"
{ adjust(yyscanner); return MODULOCHUCK;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 146 "gwion.l"
{ adjust(yyscanner); return ATCHUCK;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 147 "gwion.l"
{ adjust(yyscanner); return RSL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 148 "gwion.l"
{ adjust(yyscanner); return RSR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 149 "gwion.l"
{ adjust(yyscanner); return RSAND;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 150 "gwion.l"
{ adjust(yyscanner); return RSOR;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 151 "gwion.l"
{ adjust(yyscanner); return RSXOR;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 152 "gwion.l"
{ adjust(yyscanner); return RAND;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 153 "gwion.l"
{ adjust(yyscanner); return ROR;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 154 "gwion.l"
{ adjust(yyscanner); return REQ;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 155 "gwion.l"
{ adjust(yyscanner); return RNEQ;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 156 "gwion.l"
{ adjust(yyscanner); return RLT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 157 "gwion.l"
{ adjust(yyscanner); return RGT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 158 "gwion.l"
{ adjust(yyscanner); return RLE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 159 "gwion.l"
{ adjust(yyscanner); return RGE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 160 "gwion.l"
{ adjust(yyscanner); return PLUSPLUS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 161 "gwion.l"
{ adjust(yyscanner); return MINUSMINUS;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 162 "gwion.l"
{ adjust(yyscanner); return FUNCTION;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 163 "gwion.l"
{ adjust(yyscanner); return VARARG; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 164 "gwion.l"
{ adjust(yyscanner); return FUNC_PTR;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 165 "gwion.l"
{ adjust(yyscanner); return PROTECTED;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 166 "gwion.l"
{ adjust(yyscanner); return L_HACK;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 167 "gwion.l"
{ adjust(yyscanner); return R_HACK;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 168 "gwion.l"
{ adjust(yyscanner); return SHARPPAREN;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 169 "gwion.l"
{ adjust(yyscanner); return PERCENTPAREN;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 170 "gwion.l"
{ adjust(yyscanner); return TEMPLATE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 172 "gwion.l"
{ adjust(yyscanner); return PLUS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 173 "gwion.l"
{ adjust(yyscanner); return MINUS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 174 "gwion.l"
{ adjust(yyscanner); return DIVIDE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 175 "gwion.l"
{ adjust(yyscanner); return PERCENT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 176 "gwion.l"
{ adjust(yyscanner); return TILDA; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 177 "gwion.l"
{ adjust(yyscanner); return EXCLAMATION; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 178 "gwion.l"
{ adjust(yyscanner); return TIMES; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 179 "gwion.l"
{ adjust(yyscanner); return NEW; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 180 "gwion.l"
{ adjust(yyscanner); return TYPEOF; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 181 "gwion.l"
{ adjust(yyscanner); return SIZEOF; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 182 "gwion.l"
{ adjust(yyscanner); return SPORK; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 183 "gwion.l"
{ adjust(yyscanner); return UNION; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 185 "gwion.l"
{ adjust(yyscanner); return EQ; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 186 "gwion.l"
{ adjust(yyscanner); return NEQ; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 187 "gwion.l"
{ adjust(yyscanner); return LT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 188 "gwion.l"
{ adjust(yyscanner); return LTB; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 189 "gwion.l"
{ adjust(yyscanner); return GT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 190 "gwion.l"
{ adjust(yyscanner); return GTB; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 191 "gwion.l"
{ adjust(yyscanner); return LE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 192 "gwion.l"
{ adjust(yyscanner); return GE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 193 "gwion.l"
{ adjust(yyscanner); return AND; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 194 "gwion.l"
{ adjust(yyscanner); return OR; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 195 "gwion.l"
{ adjust(yyscanner); return S_AND; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 196 "gwion.l"
{ adjust(yyscanner); return S_OR; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 197 "gwion.l"
{ adjust(yyscanner); return S_XOR; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 198 "gwion.l"
{ adjust(yyscanner); return SHIFT_RIGHT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 199 "gwion.l"
{ adjust(yyscanner); return SHIFT_LEFT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 200 "gwion.l"
{ adjust(yyscanner); return ASSIGN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 201 "gwion.l"
{ adjust(yyscanner); return LPAREN; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 202 "gwion.l"
{ adjust(yyscanner); return RPAREN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 203 "gwion.l"
{ adjust(yyscanner); return LBRACK; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 204 "gwion.l"
{ adjust(yyscanner); return RBRACK; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 205 "gwion.l"
{ adjust(yyscanner); return LBRACE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 206 "gwion.l"
{ adjust(yyscanner); return RBRACE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 207 "gwion.l"
{ adjust(yyscanner); return QUESTION; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 208 "gwion.l"
{ adjust(yyscanner); return COLON; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 209 "gwion.l"
{ adjust(yyscanner); return COLONCOLON; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 210 "gwion.l"
{ adjust(yyscanner); return TRIG; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 211 "gwion.l"
{ adjust(yyscanner); return UNTRIG; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 214 "gwion.l"
{ adjust(yyscanner); return CLASS;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 215 "gwion.l"
{ adjust(yyscanner); return DTOR;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 216 "gwion.l"
{ adjust(yyscanner); return OPERATOR;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 217 "gwion.l"
{ adjust(yyscanner); return INTERFACE;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 218 "gwion.l"
{ adjust(yyscanner); return EXTENDS;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 219 "gwion.l"
{ adjust(yyscanner); return IMPLEMENTS;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 220 "gwion.l"
{ adjust(yyscanner); return PUBLIC;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 221 "gwion.l"
{ adjust(yyscanner); return STATIC;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 222 "gwion.l"
{ adjust(yyscanner); return PRIVATE;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 223 "gwion.l"
{ adjust(yyscanner); return ABSTRACT;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 224 "gwion.l"
{ adjust(yyscanner); return DOT;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 226 "gwion.l"
{ adjust(yyscanner); return IF;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 227 "gwion.l"
{ adjust(yyscanner); return ELSE;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 228 "gwion.l"
{ adjust(yyscanner); return BREAK;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 229 "gwion.l"
{ adjust(yyscanner); return CONTINUE;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 230 "gwion.l"
{ adjust(yyscanner); return RETURN;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 231 "gwion.l"
{ adjust(yyscanner); return WHILE;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 232 "gwion.l"
{ adjust(yyscanner); return DO;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 233 "gwion.l"
{ adjust(yyscanner); return UNTIL;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 234 "gwion.l"
{ adjust(yyscanner); return LOOP;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 235 "gwion.l"
{ adjust(yyscanner); return FOR;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 236 "gwion.l"
{ adjust(yyscanner); return GOTO;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 237 "gwion.l"
{ adjust(yyscanner); return SWITCH;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 238 "gwion.l"
{ adjust(yyscanner); return CASE;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 239 "gwion.l"
{ adjust(yyscanner); return ENUM;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 242 "gwion.l"
{ adjust(yyscanner); yylval->ival = htol(yytext);                 return NUM;        }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 243 "gwion.l"
{ adjust(yyscanner); yylval->ival = atoi(yytext);                 return NUM;        }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 244 "gwion.l"
{ adjust(yyscanner); yylval->ival = atoi(yytext);                 return NUM;        }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 245 "gwion.l"
{ adjust(yyscanner); yylval->fval = atof(yytext);                 return FLOAT;      }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 246 "gwion.l"
{ adjust(yyscanner); yylval->sval = alloc_str(yytext);           return ID;         }
	YY_BREAK
case 122:
/* rule 122 can match eol */
YY_RULE_SETUP
#line 247 "gwion.l"
{ adjust(yyscanner); yylval->sval = alloc_str(strip_lit(yytext)); return STRING_LIT; }
	YY_BREAK
case 123:
/* rule 123 can match eol */
YY_RULE_SETUP
#line 248 "gwion.l"
{ adjust(yyscanner); yylval->sval = alloc_str(strip_lit(yytext)); return CHAR_LIT;   }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 250 "gwion.l"
{ printf("error: stray in program\n"); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 251 "gwion.l"
ECHO;
	YY_BREAK
#line 1706 "lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(cdoc):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(CDOC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * minimal_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( minimal_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of minimal_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	yy_size_t number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					minimal_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			minimal_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) minimal_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 310 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 310 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 309);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					minimal_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( minimal_wrap(yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void minimal_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        minimal_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            minimal__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	minimal__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	minimal__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void minimal__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		minimal_pop_buffer_state();
	 *		minimal_push_buffer_state(new_buffer);
     */
	minimal_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	minimal__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (minimal_wrap()) processing, but the only time this flag
	 * is looked at is after minimal_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void minimal__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE minimal__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) minimal_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in minimal__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) minimal_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in minimal__create_buffer()" );

	b->yy_is_our_buffer = 1;

	minimal__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with minimal__create_buffer()
 * @param yyscanner The scanner object.
 */
    void minimal__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		minimal_free((void *) b->yy_ch_buf ,yyscanner );

	minimal_free((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a minimal_restart() or at EOF.
 */
    static void minimal__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	minimal__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then minimal__init_buffer was _probably_
     * called from minimal_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void minimal__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		minimal__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void minimal_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	minimal_ensure_buffer_stack(yyscanner);

	/* This block is copied from minimal__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from minimal__switch_to_buffer. */
	minimal__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void minimal_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	minimal__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		minimal__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void minimal_ensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)minimal_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in minimal_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)minimal_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in minimal_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE minimal__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) minimal_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in minimal__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	minimal__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to minimal_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       minimal__scan_bytes() instead.
 */
YY_BUFFER_STATE minimal__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return minimal__scan_bytes(yystr,(int) strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to minimal_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE minimal__scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) _yybytes_len + 2;
	buf = (char *) minimal_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in minimal__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = minimal__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in minimal__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE minimal_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int minimal_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int minimal_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *minimal_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *minimal_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int minimal_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *minimal_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void minimal_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void minimal_set_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "minimal_set_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void minimal_set_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "minimal_set_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see minimal__switch_to_buffer
 */
void minimal_set_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void minimal_set_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int minimal_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void minimal_set_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * minimal_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void minimal_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* minimal_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int minimal_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) minimal_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* minimal_lex_init_extra has the same functionality as minimal_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to minimal_alloc in
 * the yyextra field.
 */

int minimal_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    minimal_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) minimal_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    minimal_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from minimal_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * minimal_lex_init()
     */
    return 0;
}

/* minimal_lex_destroy is for both reentrant and non-reentrant scanners. */
int minimal_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		minimal__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		minimal_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	minimal_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        minimal_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * minimal_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    minimal_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *minimal_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *minimal_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void minimal_free (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see minimal_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 251 "gwion.l"


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "err_msg.h"


static int adjust(void* data)
{
  MyArg* arg = (MyArg*)map_get(scan_map, data);
  arg->pos += minimal_get_leng(data);
}

static int doc_adjust(void* data, char* str)
{
  MyArg* arg = (MyArg*)map_get(scan_map, data);
  arg->pos += minimal_get_leng(data);
  m_str c = vector_back(arg->doc);
  if(!c)
    vector_append(arg->doc, str);
  else
    strcat(c, str);
    printf("doc adjust\n%s\nend of doc_adjust\n", vector_front(arg->doc));
}

int minimal_error(MyArg* arg, char* s)
{
  m_uint i, pos;
  char buf[256], sign[256];
  memset(buf, 0, 256);
  memset(sign, 0, 256);
  pos = lseek(arg->fd, -arg->pos, SEEK_CUR);
  pread(arg->fd, &buf, 25, 0);
  m_str str = strdup(buf);
  str = strsep(&str, "\n");
  err_msg(PARSE_, arg->line, "in file '%s'", arg->filename);  
  err_msg(PARSE_, arg->line, "%s at pos %i\n%s", s, arg->pos, str);  
  //fprintf(stderr, )
  free(str);
  for(i = 0; i < arg->pos - 1; i++)
    strcat(sign, " ");
  strcat(sign, "^\n");
  fprintf(stderr, "%s", sign);
  return 0;
}


Map scan_map = NULL;

//Ast parse(const m_str filename)
Ast parse(m_str filename)
{
  Ast    ast  = NULL;
  FILE*  file = NULL;
  MyArg arg;
  minimal_lex_init(&arg.scanner);
  minimal_set_extra(&arg, arg.scanner);
  map_set(scan_map, arg.scanner, &arg);
  map_set(scan_map, (void*)(m_uint)minimal_get_extra(arg.scanner), &arg);
  arg.line = 1; arg.pos  = 0; arg.doc = new_Vector();
  char c[1024];
  memset(c, 0, 1024);
  strcat(c, filename);

  if(!(file = fopen(c, "r")))
  {
    err_msg(PARSE_, 0, "error while opening file '%s'.", filename);
    return NULL;
  }
  arg.fd = fileno(file);
  arg.filename = filename;
  minimal_set_in(file, arg.scanner);
  if(minimal_parse(&arg))
    return NULL;
  filename = c;
  ast = arg.ast;
  if(vector_front(arg.doc))
    ast->doc = malloc(sizeof(char));
  while(vector_front(arg.doc))
  {
    strcat(ast->doc, vector_front(arg.doc));
    vector_remove(arg.doc, 0);
  }
  fclose(file);
  return ast;
}

