name: Windows

on:
  push:
    branches:
      - "**"
      - "!gh-pages"
  pull_request:
    branches:
      - "**"
      - "!gh-pages"

jobs:
  build:
    name: Windows ${{ matrix.double && 'double' || 'float '}}
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      CC: gcc
      USE_DOUBLE: ${{ matrix.double }}
#      BUILD_ON_WINDOWS: 1
    strategy:
      matrix:
        double: [0, 1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Build
        run: make

      - name: Test
        run: make test
